/**
 * EcoTrack Knowledge Base
 * Q&A database for the chat agent — covers common carbon footprint questions.
 */

const KNOWLEDGE_BASE = [
  { keywords: ['what is', 'carbon footprint', 'define', 'meaning', 'definition'], category: 'basics', question: 'What is a carbon footprint?', answer: 'A carbon footprint is the total amount of greenhouse gases (GHGs) — primarily CO₂ — generated by your actions. It\'s measured in tonnes of CO₂ equivalent (CO₂e) per year. The global average is about 4.7 tonnes, while the US average is ~16 tonnes. To fight climate change, we need to get under 2 tonnes per person by 2050.', source: 'Nature.org / IPCC' },
  { keywords: ['how', 'calculate', 'measure', 'footprint', 'computed'], category: 'basics', question: 'How is carbon footprint calculated?', answer: 'Carbon footprint is calculated using the formula: Emissions = Activity Data × Emission Factor. For example, driving 100 km in a petrol car (emission factor: 0.21 kg/km) produces 21 kg CO₂e. We sum emissions across transport, food, energy, and lifestyle categories.', source: 'GHG Protocol' },
  { keywords: ['global', 'average', 'world', 'per person', 'mean'], category: 'basics', question: 'What is the average carbon footprint?', answer: 'The global average carbon footprint is approximately 4.7 tonnes CO₂e per person per year. However, this varies hugely by country: US (~16t), EU (~6.8t), China (~7.4t), India (~1.9t). The target to limit warming to 1.5°C is under 2 tonnes per person by 2050.', source: 'World Bank / IPCC' },
  { keywords: ['co2', 'carbon dioxide', 'greenhouse', 'ghg', 'gas'], category: 'basics', question: 'What is CO₂e?', answer: 'CO₂e (carbon dioxide equivalent) is a standard unit to compare different greenhouse gases. While CO₂ is the most common, methane (CH₄) is 80x more potent and nitrous oxide (N₂O) is 273x more potent over 20 years. CO₂e converts all GHGs into a single comparable number.', source: 'EPA' },
  { keywords: ['car', 'driving', 'vehicle', 'automobile', 'emit', 'petrol', 'diesel'], category: 'transport', question: 'How much CO₂ does a car emit?', answer: 'A typical petrol car emits about 0.21 kg CO₂ per km (or 170g CO₂/km). Diesel cars emit ~0.17 kg/km, hybrids ~0.12 kg/km, and electric cars ~0.05 kg/km (depending on the grid). Driving 15,000 km/year in a petrol car produces about 3.15 tonnes CO₂e.', source: 'DEFRA / EEA' },
  { keywords: ['electric', 'ev', 'better', 'petrol', 'gasoline', 'vs'], category: 'transport', question: 'Is an electric car better than petrol?', answer: 'Yes, even accounting for battery manufacturing, EVs produce 50-70% fewer lifetime emissions than petrol cars. An EV emits ~0.05 kg CO₂/km vs 0.21 kg/km for petrol. The gap widens as grids get greener. Over 150,000 km, an EV saves ~24 tonnes CO₂e.', source: 'Transport & Environment' },
  { keywords: ['flight', 'flying', 'airplane', 'plane', 'aviation', 'air travel'], category: 'transport', question: 'How much CO₂ does flying produce?', answer: 'Flying is one of the most carbon-intensive activities. A return flight from NYC to London produces ~1.6 tonnes CO₂e per passenger — that\'s nearly the entire annual sustainable budget per person! Short-haul flights emit about 0.255 kg/km, long-haul about 0.195 kg/km per passenger.', source: 'ICAO / atmosfair' },
  { keywords: ['bus', 'train', 'public', 'transport', 'transit', 'metro', 'subway'], category: 'transport', question: 'How does public transport compare?', answer: 'Public transport is significantly greener: buses emit ~0.089 kg CO₂/km per passenger, trains ~0.041 kg/km, and metros ~0.033 kg/km. That\'s 60-85% less than a single-occupancy car (0.21 kg/km). Switching from car to train for a 20 km daily commute saves ~1.5 tonnes CO₂ per year!', source: 'DEFRA / IEA' },
  { keywords: ['beef', 'meat', 'food', 'highest', 'worst', 'carbon'], category: 'food', question: 'Which food has the highest carbon footprint?', answer: 'Lamb tops the list at 39.2 kg CO₂e per kg, followed by beef at 27 kg/kg. For context, 1 kg of beef produces as much CO₂ as driving 100 km! Cheese (13.5 kg/kg) and chocolate (19 kg/kg) are also high. In contrast, vegetables (2 kg/kg) and legumes (0.9 kg/kg) are very low-impact.', source: 'Our World in Data / Poore & Nemecek' },
  { keywords: ['vegan', 'vegetarian', 'plant', 'diet', 'food impact'], category: 'food', question: 'How much does diet affect carbon footprint?', answer: 'Diet has a huge impact! A heavy meat diet produces ~330 kg CO₂e/month vs just ~85 kg for a vegan diet — that\'s a 74% reduction. Going vegetarian saves about ~1 tonne CO₂e per year. Even reducing meat to 2 days per week can save ~500 kg CO₂e annually.', source: 'Science / Poore & Nemecek 2018' },
  { keywords: ['chicken', 'beef', 'compare', 'worse', 'better', 'vs'], category: 'food', question: 'Is beef or chicken worse for the environment?', answer: 'Beef is significantly worse — it produces 27 kg CO₂e per kg compared to chicken at 6.9 kg/kg. That\'s nearly 4x the impact! Beef also uses 20x more land and 7x more water. Simply swapping beef for chicken can reduce food-related emissions by 50-60%.', source: 'Our World in Data' },
  { keywords: ['electricity', 'energy', 'power', 'grid', 'kWh'], category: 'energy', question: 'How much CO₂ does electricity produce?', answer: 'The global average is about 0.42 kg CO₂ per kWh, but this varies enormously by region. Coal-heavy grids (Australia, Poland) can exceed 0.7 kg/kWh, while renewable-heavy grids (Norway, Iceland) are below 0.05 kg/kWh. An average household using 300 kWh/month produces ~126 kg CO₂.', source: 'IEA / Ember' },
  { keywords: ['renewable', 'solar', 'wind', 'clean', 'green energy'], category: 'energy', question: 'How much do renewables help?', answer: 'Switching to 100% renewable energy can cut your electricity emissions by up to 95%. Solar panels produce only 0.05 kg CO₂/kWh (lifecycle), wind just 0.01 kg/kWh, compared to coal at 1.0 kg/kWh. A typical rooftop solar system saves 1.5-2 tonnes CO₂ per year.', source: 'IPCC / NREL' },
  { keywords: ['offset', 'carbon offset', 'carbon credit', 'neutralize', 'compensate'], category: 'offsets', question: 'How do carbon offsets work?', answer: 'Carbon offsets let you compensate for your emissions by funding projects that reduce CO₂ elsewhere — like reforestation, renewable energy, or methane capture. One "offset credit" = 1 tonne CO₂e removed or avoided. However, experts recommend reducing emissions first and offsetting what you can\'t eliminate. Look for Gold Standard or VCS certified offsets.', source: 'Gold Standard / Verra' },
  { keywords: ['tree', 'trees', 'plant', 'planting', 'forest', 'absorb'], category: 'offsets', question: 'How many trees to offset my footprint?', answer: 'A mature tree absorbs about 22 kg of CO₂ per year. To offset the global average (4.7t), you\'d need ~214 trees. For the US average (16t), you\'d need ~727 trees! While tree planting helps, it takes decades for trees to mature. Reducing emissions at the source is far more effective.', source: 'USDA Forest Service' },
  { keywords: ['paris', 'agreement', 'climate', 'accord', 'policy', 'treaty'], category: 'climate_science', question: 'What is the Paris Agreement?', answer: 'The Paris Agreement (2015) is a landmark global treaty where 196 countries agreed to limit global warming to well below 2°C, preferably 1.5°C above pre-industrial levels. To achieve this, global emissions must fall 45% by 2030 and reach net zero by 2050. Each country sets its own reduction targets (NDCs).', source: 'UNFCCC' },
  { keywords: ['1.5', 'degrees', 'warming', 'temperature', 'climate change', 'global warming'], category: 'climate_science', question: 'Why does 1.5°C matter?', answer: 'At 1.5°C warming, we face more heatwaves, rising seas, and biodiversity loss — but the damage is far less than at 2°C. The difference between 1.5°C and 2°C means: 2x more people facing water scarcity, 70% vs 99% of coral reefs dying, and 6 vs 16 million more affected by sea level rise. Every fraction of a degree matters.', source: 'IPCC SR15' },
  { keywords: ['streaming', 'netflix', 'video', 'internet', 'digital', 'online'], category: 'lifestyle', question: 'Does streaming video produce CO₂?', answer: 'Yes! Streaming 1 hour of video produces about 36g of CO₂ due to data centers, networks, and device energy. Watching 4 hours daily for a year equals ~53 kg CO₂ — roughly equivalent to a short domestic flight. Lowering video quality from 4K to HD can reduce this by up to 86%.', source: 'IEA / Carbon Trust' },
  { keywords: ['fast fashion', 'clothes', 'clothing', 'textile', 'fashion'], category: 'lifestyle', question: 'What is the carbon cost of fashion?', answer: 'The fashion industry accounts for ~10% of global carbon emissions — more than aviation and shipping combined! A single cotton t-shirt produces ~8 kg CO₂, while a pair of jeans produces ~33 kg CO₂. Buying secondhand, choosing quality over quantity, and extending garment life by just 9 months reduces carbon impact by ~30%.', source: 'UNEP / Ellen MacArthur Foundation' },
  { keywords: ['recycle', 'recycling', 'waste', 'garbage', 'landfill'], category: 'lifestyle', question: 'Does recycling really help?', answer: 'Yes! Recycling aluminum saves 95% of the energy vs making new aluminum. Recycling paper saves 60%, and plastics saves 30-80%. Recycling also reduces methane from landfills — a gas 80x more potent than CO₂. Composting food waste is equally important, as food in landfills generates significant methane.', source: 'EPA / WRAP' },
  { keywords: ['water', 'shower', 'bath', 'tap'], category: 'lifestyle', question: 'How does water use affect carbon footprint?', answer: 'Heating water accounts for ~17% of home energy use. A 5-minute shower uses ~0.5 kg CO₂e, while a bath uses ~2.5 kg. Cutting shower time by 2 minutes saves ~25 kg CO₂ per year. Cold water washing clothes saves ~0.3 kg CO₂ per load compared to hot wash.', source: 'Energy Saving Trust' },
  { keywords: ['reduce', 'lower', 'decrease', 'cut', 'tips', 'how can i'], category: 'basics', question: 'How can I reduce my carbon footprint?', answer: 'The biggest actions you can take: 1) 🚆 Use public transport or bike instead of driving (-1.5t/year), 2) 🥗 Eat less meat, especially beef (-1t/year), 3) ☀️ Switch to renewable energy (-1.5t/year), 4) ✈️ Fly less (-1.6t per return long-haul flight), 5) 🛍️ Buy less fast fashion (-0.3t/year). Start with the easiest changes — every action counts!', source: 'Project Drawdown' },
  { keywords: ['biggest', 'largest', 'most', 'source', 'contributor', 'cause'], category: 'basics', question: 'What contributes most to carbon footprint?', answer: 'Globally, the biggest contributors are: Energy/electricity (25%), Industry (21%), Transport (16%), Buildings (6%), Agriculture (10%). For individuals, the ranking depends on lifestyle, but typically: 1) Transport (especially flying/driving), 2) Home energy, 3) Food, 4) Consumer goods. Your biggest source depends on your habits!', source: 'IPCC AR6' },
];

export function findAnswer(query) {
  const queryLower = query.toLowerCase().trim();
  const queryWords = queryLower.split(/\s+/);

  let bestMatch = null;
  let bestScore = 0;

  for (const entry of KNOWLEDGE_BASE) {
    let score = 0;
    for (const keyword of entry.keywords) {
      const keywordLower = keyword.toLowerCase();
      if (queryLower.includes(keywordLower)) {
        score += keywordLower.split(' ').length * 2;
      } else {
        for (const word of queryWords) {
          if (keywordLower.includes(word) && word.length > 2) score += 1;
        }
      }
    }
    if (score > bestScore) {
      bestScore = score;
      bestMatch = entry;
    }
  }

  if (bestScore >= 2) {
    return { found: true, ...bestMatch };
  }

  // Suggest closest matches
  const suggestions = KNOWLEDGE_BASE
    .map(e => ({ question: e.question, score: e.keywords.filter(k => queryWords.some(w => k.includes(w))).length }))
    .filter(s => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 3)
    .map(s => s.question);

  return { found: false, suggestions, message: "I'm not sure about that exact question. Here are some related topics I can help with:" };
}

export function getRandomQuestion() {
  return KNOWLEDGE_BASE[Math.floor(Math.random() * KNOWLEDGE_BASE.length)];
}

export function getQuestionsByCategory(category) {
  return KNOWLEDGE_BASE.filter(e => e.category === category);
}
